### ISSUE TITLE
Attachment File Upload Problem

### ISSUE THREAD

**Issue by ismet** [koltyakov/sp-rest-proxy#15] opened 2017-05-04 07:40 UTC
Hi,

I'm trying to add an item with an attachment to a list. Adding an item is OK, but adding an attachment is problematic. The code is below;

```
pnp.sp.lists.getByTitle("MyList").items.add(item).then(response => {
    response.item.attachmentFiles.add("file.txt", "file content 123");
});
```

The error:

```
POST http://localhost:8383/MyList')/items(11)/AttachmentFiles/add(FileName='file.txt') 400 (Bad Request)
Fetch API cannot load http://localhost:8383/MyList')/items(11)/AttachmentFiles/add(FileName='file.txt'). 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Uncaught (in promise) TypeError: Failed to fetch
```

Headers:

```
General
    Request URL: http://localhost:8383/_api/web/lists/getByTitle('MyList')/items(11)/AttachmentFiles/add(FileName='file.txt')
    Request Method:POST
    Status Code:400 Bad Request
    Remote Address:127.0.0.1:8383
    Referrer Policy:no-referrer-when-downgrade
Response Headers
    Connection:keep-alive
    Content-Length:1048
    Content-Security-Policy:default-src 'self'
    Content-Type:text/html; charset=utf-8
    Date:Thu, 04 May 2017 07:30:25 GMT
    X-Content-Type-Options:nosniff
    X-Powered-By:Express
Request Headers
    accept:application/json
    Accept-Encoding:gzip, deflate, br
    Accept-Language:en-US,en;q=0.8
    Connection:keep-alive
    Content-Length:14
    content-type:application/json;odata=verbose;charset=utf-8
    Host:localhost:8383
    Origin:http://localhost:8080
    Referer:http://localhost:8080/
    User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.36 Safari/537.36
    x-clientservice-clienttag:PnPCoreJS:2.0.4
    x-requestdigest:0xB1B9800178D92F1E17AAE31002BA4F4608B210FCFFDC51F863494EEDBCD5C541781BC78F35C5103F93E4163D10CF81F64AE92C257DB818F38015C4B2CBE21D0F,04 May 2017 07:30:02 -0000
Request Payload
    file content 123

```

I think, the proxy server responses lack **Access-Control-Allow-Origin** header for this type of requests.

How can we solve it?

**Comment by koltyakov** [comment] 2017-05-04 07:46
Thanks for reporting. I'll figure it out. And come back to you.
With current workload, it likely will happen on this weekend.

**Comment by ismet** [comment] 2017-05-08 07:20
Hi @koltyakov,

Any news on the fix?

**Comment by koltyakov** [comment] 2017-05-08 07:34
Hi @ismet,

Yep, there are some news and investigations. But have not been able to manage it working, still. 
The issue is connected with express bodyParser. It works nicely with json bodies.
But when an attachment is posted, the middleware goes crazy. So, I'm struggling with express middlewares to make this work.

Please bear with me and stay tuned. Hope to kill this beast soon by injecting custom middleware.

**Comment by koltyakov** [comment] 2017-05-08 10:45
It should work now.
Published the lib with the version 2.0.0-beta5
Going to leave it in beta and in Dev branch until some integration test won't be completed.

**Comment by ismet** [comment] 2017-05-08 11:37
Hello @koltyakov,

Thank you for all the efforts.. I updated sp-rest-proxy to 2.0.0-beta5 and re-run the code. Unfortunately there are some other problems.. 

- If I upload a text file (<100KB), it simply works!
- If I upload a text file (>100KB), it doesn't upload the file. I get HTTP 413 (Payload Too Large) error.
- If I upload a non-text(image, doc, etc.) file (<100KB), it uploads the file but the file becomes corrupted (cannot be opened)
- If I upload a non-text(image, doc, etc.) file (>100KB), it doesn't upload anything and complains about the large payload.

I wish I were that experienced to identify the problems and contribute to your project.

**Comment by koltyakov** [comment] 2017-05-08 11:54
Oh, shoot! =( It was a default bodyParse limit. Have extended the default 100KB up to 2MB.

> - If I upload a non-text(image, doc, etc.) file (<100KB), it uploads the file but the file becomes corrupted (cannot be opened)
> - If I upload a non-text(image, doc, etc.) file (>100KB), it doesn't upload anything and complains about the large payload.

You are right, it now only works for plain text attachments. Thanks for pointing in it.

> I wish I were that experienced to identify the problems and contribute to your project.

Not a problem. Your comments, actually, are really helpful.

**Comment by ismet** [comment] 2017-05-08 12:10
> Have extended the default 100KB up to 2MB.

How about removing the limits? Because we need to upload bigger files. Or can we define the limit size as a parameter in config file?

> It now only works for plain text attachments.

How much work does it need to make upload work for any kind of file?

**Comment by koltyakov** [comment] 2017-05-08 12:29
`IProxySettings` parameters are extended with `rawBodyLimitSize` parameter. String in [bytes](https://www.npmjs.com/package/bytes) format.
Switched from plain text to buffer and added `processData: false` to the request options. But have no chance to test with images and other files format.

> How much work does it need to make upload work for any kind of file?
I hope that I will be able to do it tonight. Just hate to leave something not finished. =)

**Comment by ismet** [comment] 2017-05-08 12:54
Ooops, something seems broken with these changes..

I can't even add a new item to a list. I get the following error:
`
http://localhost:8383/_api/contextinfo 404 (Not Found)
`

Looks like there is a problem with POST request..

**Comment by koltyakov** [comment] 2017-05-08 13:34
Oh, that's strange, I thought I checked add item and add attachment integration tests before leave. My bad, applied something in a blind. Please use previous beta by installing 'npm install sp-rest-proxy@2.0.0-beta6 --save'. I'm far from the computer at the moment to check and fix.

**Comment by koltyakov** [comment] 2017-05-08 17:41
It works for me now.
Documents of all formats can be uploaded as a buffer array.
I've tested in with http://localhost:8080/test/attachments.html quick test page, the same exactly script published to SharePoint page worked identically.
Closing the issue.

**Closed by koltyakov** 2017-05-08 17:41 UTC
Labels: bug

**Comment by ismet** [comment] 2017-05-08 19:01
It works like a charm.. Thank you!

Just one thing.. rawBodyLimitSize value doesn't override your default settings ("2mb"). I can not upload a file bigger than 2MB..

**Comment by koltyakov** [comment] 2017-05-08 20:29
@ismet, are you sure?
It worked for me well with a file around 4MB.
Settings should be provided like this:

```javascript
// server.js
var path = require('path');
var RestProxy = require('./index');
var settings = {
    configPath: path.join(__dirname, '/../config/private.json'),
    staticRoot: path.join(__dirname, '/../static'),
    rawBodyLimitSize: '4MB'
};
(new RestProxy(settings)).serve();
```

**Comment by ismet** [comment] 2017-05-09 05:56
@koltyakov, sorry, it was my mistake.. I had put rawBodyLimitSize into _private.conf.json instead of settings object.

Now, attachment upload is fully functional.. And you're a hero! :)
