### ISSUE TITLE
Unexpected close tag\nLine: 30\nColumn: 10\nChar: >

### ISSUE THREAD

**Issue by lenard-a** [koltyakov/sp-rest-proxy#121] opened 2021-01-24 14:36 UTC
Can't send any request with version 3.0.3

Response error:
{
  "readyState": 4,
  "responseText": "Proxy Error: Unexpected close tag\nLine: 30\nColumn: 10\nChar: > (see more in sp-rest-proxy console)",
  "status": 400,
  "statusText": "Bad Request"
}

Config: : SP Online,  UserCredentials

**Comment by koltyakov** [comment] 2021-01-24 14:45
Hi @lenard-a, 

Can't reproduce. With 3.0.3 all the integration tests as well as manual are OK. Any idea, how to repro?
What's in Node.js console logs? What endpoint is called before the error?

**Comment by koltyakov** [comment] 2021-01-24 14:52
Also, the diff with the previous version, which have been there published for 4 months, is a security patch for one of the dependencies that is only used in a gateway mode. So I'm more than sure that no issues could been introduced.

**Comment by lenard-a** [comment] 2021-01-24 22:04
Thank you for the quick answer. Sorry that I implied that the issue was caused some change in the current version. This is the first version I used, and I just shared it with you to help debugging. I found a workaround by using the OnDemandCredentials instead of UserCredentials, but I will check the console logs and share it with you later.
I tried to call the /_api/web/lists/getbytitle('listname') endpoint.

**Comment by koltyakov** [comment] 2021-01-25 07:53
Oh, that's auth thing. Initially I thought that you've been using 3.0.2 then upgraded to 3.0.3.

Glad that OnDemand works for you.

SharePoint has lots of auth options and external factors, like CAS, MFA. Sometimes one could try using unsupported external accounts.

Authentication is external dependency for sp-rest-proxy. Auth is happening thanks to [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth). As a separation layer for troubleshooting I'd suggest this helper project https://github.com/koltyakov/node-sp-auth-troubleshoot to check only auth-related part.

Thanks for using the libraries! Closing the issue.

**Closed by koltyakov** 2021-01-25 07:53 UTC

**Comment by sankarkumar23** [comment] 2021-11-18 12:29
I am using version 3.1.0 but getting the same above error. I am trying to connect to SPO with User credentials. Any pointers?
