### ISSUE TITLE
Check error responses

### ISSUE THREAD

**Issue by koltyakov** [koltyakov/sp-rest-proxy#38] opened 2017-12-07 06:53 UTC
https://github.com/SharePoint/PnP-JS-Core/issues/652

**Comment by koltyakov** [comment] 2017-12-07 10:27
I have applied some changes in Err responses. On the test use cases after changes sp-rest-proxy showed identical responses as while requesting REST API being on SP pages.
Yet some testing might be required.
@brunoferreira2007, could you please check if v 2.5.2 fixes your issue with PnP JS Core and 404 err catches?

**Comment by brunoferreira2007** [comment] 2017-12-07 15:33
Hi @koltyakov ,

Yes, the issue is fixed now. thanks
![image](https://user-images.githubusercontent.com/33944868/33723169-cd364cfa-db63-11e7-9a8f-4534379a164e.png)

**Comment by koltyakov** [comment] 2017-12-07 15:37
Cool! Once again, thank you for finding this out.
Closing the issue.

**Closed** 2017-12-08 07:46 UTC
