### ISSUE TITLE
SharePoint Online, MFA with Ping not working

### ISSUE THREAD

**Issue by esandeep** [koltyakov/sp-rest-proxy#67] opened 2018-11-13 19:38 UTC
SO there are two issues came across
1. Electron package missing- I was able to install electron and fix this
2. The MFA not working-I tried on-demand which I think i correct option for a SPO instance that uses PingID and MFA. But I get an error that complains about status code. Am I doing something wrong or missing something?
Unhandled rejection TypeError: Cannot read property 'statusCode' of undefined
    at RestGetRouter.BasicRouter.transmitError (sp-rest-proxy-master\src\core\BasicRouter.ts:39:25)
    at sp-rest-proxy-master\src\core\routers\restGet.ts:56:26
    at tryCatcher (sp-rest-proxy-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (sp-rest-proxy-master\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (sp-rest-proxy-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (sp-rest-proxy-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (sp-rest-proxy-master\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (sp-rest-proxy-master\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (sp-rest-proxy-master\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (sp-rest-proxy-master\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (sp-rest-proxy-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)

Regards

**Comment by koltyakov** [comment] 2018-11-13 20:01
Hi @esandeep,

Electron is an optional dependency in node-sp-auth library, as Electron is a heavy one and on-demand not necessarily needed in every installation, so it assumes that it's installed globally or locally only when needed. 

MFA requires some extra configuration steps. Please check [this](https://github.com/s-KaiNet/gulp-spsave/issues/31#issuecomment-360161754) out.

Can you try to follow auth troubleshooting steps? This [project](https://github.com/koltyakov/node-sp-auth-troubleshoot) could separate authentication issues if any.

**Comment by esandeep** [comment] 2018-11-13 20:07
I did try some troubleshooting and below is the error message I get in the transmitError method:

{ Error: Command failed: C:\WINDOWS\system32\cmd.exe /d /s /c "electron sp-rest-proxy-master\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\electron\main.js `{SPSiteURL}` false"
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at OnDemand.saveAuthData (sp-rest-proxy-master\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:80:37)
    at OnDemand.getAuth (sp-rest-proxy-master\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:39:28)
    at Object.getAuth (sp-rest-proxy-master\node_modules\node-sp-auth\lib\src\index.js:8:76)
    at sp-rest-proxy-master\node_modules\sp-request\lib\src\core\SPRequest.js:40:20
    at Promise._execute (sp-rest-proxy-master\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (sp-rest-proxy-master\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (sp-rest-proxy-master\node_modules\bluebird\js\release\promise.js:79:10)
    at coreRequest (sp-rest-proxy-master\node_modules\sp-request\lib\src\core\SPRequest.js:22:16)
    at spRequestFunc (sp-rest-proxy-master\node_modules\sp-request\lib\src\core\SPRequest.js:69:20)
    at Function.spRequestFunc.(anonymous function) [as get] (sp-rest-proxy-master\node_modules\sp-request\lib\src\core\SPRequest.js:109:24)
    at RestGetRouter._this.router (sp-rest-proxy-master\src\core\routers\restGet.ts:40:14)
    at Layer.handle [as handle_request] (sp-rest-proxy-master\node_modules\express\lib\router\layer.js:95:5)
    at next (sp-rest-proxy-master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (sp-rest-proxy-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (sp-rest-proxy-master\node_modules\express\lib\router\layer.js:95:5)
    at sp-rest-proxy-master\node_modules\express\lib\router\index.js:281:22
    at param (sp-rest-proxy-master\node_modules\express\lib\router\index.js:354:14)
    at param (sp-rest-proxy-master\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (sp-rest-proxy-master\node_modules\express\lib\router\index.js:410:3)
    at next (sp-rest-proxy-master\node_modules\express\lib\router\index.js:275:10)
  status: 4294967295,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 18100,
  stdout: <Buffer >,
  stderr: <Buffer > }

**Comment by esandeep** [comment] 2018-11-13 20:19
the troubleshoot project gets me this Error:
=== Error ===
 { Error: Command failed: C:\WINDOWS\system32\cmd.exe /d /s /c "electron \node-sp-auth-troubleshoot\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\electron\main.js {URL}false"
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at OnDemand.saveAuthData (node-sp-auth-troubleshoot\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:80:37)
    at OnDemand.getAuth (node-sp-auth-troubleshoot\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:39:28)
    at getAuth (node-sp-auth-troubleshoot\node_modules\node-sp-auth\lib\src\index.js:8:76)
    at node-sp-auth-troubleshoot\index.js:22:30
  status: 4294967295,  signal: null,  output: [ null, <Buffer >, <Buffer > ],
  pid: 2908,
  stdout: <Buffer >,
  stderr: <Buffer > }

**Comment by koltyakov** [comment] 2018-11-13 20:21
Can't reproduce on my SPO environments, all work with On-Demand too, however, I'm not using MFA.
Please check will it be any weirdies here:

![image](https://user-images.githubusercontent.com/7816483/48440561-3f6eb580-e79a-11e8-8c2d-73abd43e693d.png)

Looks as machine/environment specific.

Anyway, app password or Add-In only permissions auth strategies should be an extra options to authenticate agains the environmet.

**Comment by koltyakov** [comment] 2018-11-14 07:58
> { Error: Command failed: C:\WINDOWS\system32\cmd.exe /d /s /c "electron \node-sp-auth-troubleshoot\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\electron\main.js {URL}false"

Did you just replace site URL with a `{URL}` hash while copying pasting or it an actual message and siteUrl is not provided? 

Did you manage to try Add-In Only permissions or app password, btw?

**Comment by esandeep** [comment] 2018-11-15 00:03
So this is interesting. I tried a few older versions and finally got success in this combination:

1. The SPRestProxy- 9a1792ca4b8fd36baeb962bdc051aa004299ef1f WHich was committed on Oct 23rd 2018
2. Electron version 1.8.2- npm install electron@1.8.2 --save-dev --save-exact

And nos it seems to be working fine.

**Comment by koltyakov** [comment] 2018-11-15 07:55
Interesting observation. Will check my local version of electron. As, as I said before, On-Demand works for me. If it’s really versions compatibility issues will commute with @s-kainet on possibility to impoove this.

**Comment by s-KaiNet** [comment] 2018-11-15 09:58
@esandeep thanks for the info, I added an issue in `node-sp-auth` repository.

**Comment by esandeep** [comment] 2018-11-15 19:38
Since we are talking about MFA, let me share another observation here. 
So when I deploy this proxy on a machine that is on my client's domain, then it works all fine. However, if I try the same proxy on my personal laptop, which obliviously is not on client's domain, I get the PingID prompt in electron window, but after entering the token value, the window doesn't go away. 

I can access the SPO site from my personal laptop and it works fine in browser, it shows the second factor PingID window in browser, accepts token value, and takes me to the SPO site. It just doesn't work in electron window on a machine that's not on domain.

**Comment by koltyakov** [comment] 2018-11-23 12:00
Should be fixed by forcing the installation of the latest node-sp-auth version.

**Closed by koltyakov** 2018-11-23 12:00 UTC
